### ISSUE TITLE
Broken docs links

### ISSUE THREAD

**Issue by pambrose** [Flaxoos/extra-ktor-plugins#25]
The Redis, JDBC, MongoDB and Core links on https://flaxoos.github.io/extra-ktor-plugins/ktor-server-task-scheduling/
are broken.

**Comment by Flaxoos** [comment]
[Fixed](https://github.com/Flaxoos/extra-ktor-plugins/commit/eecf39709c4a45e9854c1fd7a2c00c13fb0dacb3)

@pambrose thanks for reporting this
