### ISSUE TITLE
Qestion - how to set up additional propertise for Kafka

### ISSUE THREAD

**Issue by KamilNadlonek-TomTom** [Flaxoos/extra-ktor-plugins#26]
I want to set up property "sasl.jaas.config" - https://kafka.apache.org/21/javadoc/index.html?org/apache/kafka/common/config/package-summary.html (SASL_JAAS_CONFIG)
How can I set this up?

**Comment by Flaxoos** [comment]
Hi Kamil, i just saw your issue, i need to adjust my notification settings. Let me look into it

**Comment by Flaxoos** [comment]
Hi Kamil, You're right, these are missing. 

I'll create a task for it
