### ISSUE TITLE
Subject for new Avro schema 

### ISSUE THREAD

**Issue by diegopatinor** [Flaxoos/extra-ktor-plugins#32]
Hello, I need to send various types of messages on the same topic (User Created, User Updated, User Deleted for example), but the schema registration always uses the subject `TopicName(value=my-topic)-value`. This prevents me from registering multiple schemas for the same topic.

```
ERROR: Failed registering schema to schema registry at http://localhost:8081/subjects/TopicName(value=my-topic)-value/versions:
409 Conflict {\"error_code\":409,\"message\":\"Schema being registered is incompatible with an earlier schema for subject \\\"TopicName(value=my-topic)-value
```

From what I see, this is hardcoded at [Avro.kt](https://github.com/Flaxoos/extra-ktor-plugins/blob/main/ktor-server-kafka/src/jvmMain/kotlin/io/github/flaxoos/ktor/server/plugins/kafka/components/Avro.kt) line 70. Could the subject be registered as `topicName.AvroSchemaName` as other implementations do, allowing multiple schemas related to the same topic to be registered?

Regards!

**Comment by diegopatinor** [comment]
Hi @Flaxoos, have you looked at this?

**Comment by Flaxoos** [comment]
I did, I thought you’re going to add a test for this?

**Comment by diegopatinor** [comment]
Yes, sorry, I didn't see the comment. The test was added.
