### ISSUE TITLE
kafka: how to seekToBeginning

### ISSUE THREAD

**Issue by Kinchkun** [Flaxoos/extra-ktor-plugins#69]
Cheers,

thank you for your plugins :)

I am new to kafka. I want to always consume from the beginning of a topic. My use case is to rebuild an index at the start of an application. I know that you can achieve this by setting a random group-id and set `autoOffsetReset` to `earliest`. 

I wonder if its possible to use the `KafkaConsumer.seekToBeginning` method however. I tried several approaches but none seems to work.

```kotlin
installKafka {
  // configuration
  consumerConfig {
    consumerRecordHandler(topic) {
      // handle record
    }
  }
}

kafkaConsumer?.seekToBeginning(emptyList())
```

However, at this point the kafkaConsumer isn't subscribed to a topic yet.

```kotlin
installKafka {
  // configuration
  consumerConfig {
    consumerRecordHandler(topic) {
      // handle record
     if(first) {
       kafkaConsumer?.seekToBeginning(emptyList())
       first = false
     }
    }
  }
}
```

This works a little bit, but only after one message was received.

Do you now how to solve this? 

Kind regards
Kinch

**Comment by Flaxoos** [comment]
Hey @Kinchkun 
I'm not sure if you're having trouble with the plugin or with the kafka api. 
In any case, in your first code snippet, as you correctly said, _kafkaConsumer isn't subscribed to a topic yet._ more precisly, the application didn't start yet. To do something upon start of the application you should use [ktor server events](https://ktor.io/docs/server-events.html#predefined-events). at this point you could get the _kafkaConsumer which shouldn't be null if the server started already.

regarding seekToBeginning, the documentation says:

>Seek to the first offset for each of the given partitions. This function evaluates lazily, seeking to the first offset in all partitions only when {@link #poll(Duration)} or {@link #position(TopicPartition)} are called. If no partitions are provided, seek to the first offset for all of the currently assigned partitions.

So you're supposed to call poll first

Does that make sense/help you?

**Comment by Flaxoos** [comment]
@Kinchkun Happy to help. I'd suggest getting familiar with Ktor a bit more, there's isn't a lot of concepts to cover and the documentation is very good
