### ISSUE TITLE
Rate limiter not adding headers to response by default

### ISSUE THREAD

**Issue by king-phyte** [Flaxoos/extra-ktor-plugins#77]
Hello. Thank you for your work on this package.

I am using **ktor-server-rate-limiting:2.1.1** and I noticed that the response headers (`X-RateLimit-*`) are not being sent in the response. I think this is happening because the headers are set **after** calling `respond` [as seeen here](https://github.com/Flaxoos/extra-ktor-plugins/blob/d0b1546246ddd84cafe2fdcbcd0d1011e0adff2b/ktor-server-rate-limiting/src/commonMain/kotlin/io/github/flaxoos/ktor/server/plugins/ratelimiter/RateLimitingConfiguration.kt#L84), so maybe they are ignored? I am not sure since I am quite new to Ktor. See the sample below:

```kotlin
install(RateLimiting) {
            rateLimiter {
                type = TokenBucket::class
                rate = 1.seconds
                capacity = 5
                clock = { Instant.now().toEpochMilli() }
                callVolumeUnit = CallVolumeUnit.Calls()
            }

            rateLimitExceededHandler = { limitedBy ->
                respond( // <--- respond called here
                    status = HttpStatusCode.TooManyRequests,
                    message = mapOf("error" to "Rate limit exceeded")
                )
                // <--- headers are being set here
                // This is how it is currently. And they don't show up in the response.
                response.headers.append(HttpHeaders.RetryAfter, "${limitedBy.resetIn.inWholeSeconds}")
                response.headers.append("X-RateLimit-Limit", "${limitedBy.rateLimiter.capacity}")
                response.headers.append("X-RateLimit-Reset", "${limitedBy.resetIn.inWholeMilliseconds}")
            }
        }
```

Headers in resposnse
```
connection: keep-alive
content-type: application/json
transfer-encoding: chunked
vary: Origin
```

By moving the headers in the handler above the call to `respond`, they show up i.e. the handler below works

```kotlin
rateLimitExceededHandler = { limitedBy ->
                response.headers.append(HttpHeaders.RetryAfter, "${limitedBy.resetIn.inWholeSeconds}")
                response.headers.append("X-RateLimit-Limit", "${limitedBy.rateLimiter.capacity}")
                response.headers.append("X-RateLimit-Reset", "${limitedBy.resetIn.inWholeMilliseconds}")
                respond( // <--- response called after headers
                    status = HttpStatusCode.TooManyRequests,
                    message = mapOf("error" to "Rate limit exceeded")
                )
            }
```

Headers in response

```
connection: keep-alive
content-type: application/json
retry-after: 1
transfer-encoding: chunked
vary: Origin
x-ratelimit-limit: 5
x-ratelimit-reset: 1000 
```

If I am misunderstanding something or you need extra information, please let me know. Thank you

**Comment by Flaxoos** [comment]
Hi @king-phyte, thank you for spotting this!
Without trying it out myself, i'd say it definitely makes sense. Would you like to create a PR for this fix?
In any case, in the meantime, it can be solved by providing the corrected handler, overriding the default one (as you showed above)

**Comment by king-phyte** [comment]
@Flaxoos Thank you for the swift response. I would love to create the PR. I will submit it soon

About the handler, I did use the "corrected" handler but I have installed the plugin on different routes (for different resource constraints) so I have had to do a bit of copy paste. Nothing crazy though.

Thank you!

**Comment by Flaxoos** [comment]
@king-phyte Released :)

**Comment by king-phyte** [comment]
Excellent!

From the docs page, the version didn't get updated. Everywhere else if fine though, I think. Is that okay?
<img width="232" alt="image" src="https://github.com/user-attachments/assets/864eb210-f158-45ef-9041-7ad28c6a816e" />

**Comment by Flaxoos** [comment]
Yeah it takes a bit for sonatype to process

**Comment by king-phyte** [comment]
Oh I see. Understandable. Thank you for everything!
Stay awesome 🤩
